#!/bin/sh

# Sent output of a command to a file

### List a directory to "mylist.txt"
ls > mylist.txt

### grep to "mygrep.txt"
grep "foo" * > mygrep.txt


# Combine different commands

## Command as variable
### Find .html files and grep it for contents "Ink is a verb", show line number & filename
grep -nH "Ink is a verb" $(find -type f -name "*.html")

## -exec ....... {} +
### Find .html files and grep it for contents "Ink is a verb" show line number & filename
find .-type -f -iname "*.html" -exec grep -i -nH "Ink is a verb" {} +

## xargs
### Find 'foo' and replace with 'bar' recursively with grep
grep -rl 'foo' * | xargs sed -i 's/foo/bar/g'
