#!/bin/sh

# The "find" command

## Options

### Name
#### exact name: -name
#### ignore case: -iname

### Type
#### files and directoryes: (nothing)
#### files: -type f
#### directories: -type d

### Permissions
#### 664 permissions: -perm 0664
#### 777 permissions: -perm 0777

### Size
#### Over 100kb: -size +100k
#### Exactly 1MB: -size 1M
#### Under 1MB: -size -1M

### NOT
#### Not *.php any case: -not -iname "*.php"
#### Not *.PNG: -not -name "*.PNG"

### Recursive directory depth
#### Only this directory: -maxdepth 1
#### Into two lower directories: -maxdepth 3


## Examples
find /dir/path -type f -name "filename.ext"
find /dir/path -type f -iname "filename.ext"

