#!/bin/sh

# Perform a test with response
if [ THIS IS THE TEST ]
then
DO THIS IN RESPONSE
fi

# Perform a test with else otherwise response
if [ THIS IS THE TEST ]
then
DO THIS IN RESPONSE
else
DO THIS OTHERWISE
fi

# Put if-then on one line
if [ THIS IS THE TEST ]; then
DO THIS IN RESPONSE
fi

# Put everything on one line
if [ THIS IS THE TEST ]; then; DO THIS IN RESPONSE; fi

# Test with grep if "foo" is in a file
if grep -Fq "foo" /path/to/file; then
echo "foo is true"
fi

# Test if a file exists
if [ -f /path/to/file ]; then
echo "It's alive!"
fi

# Test if a directory exists
if [ -d /path/to/directory ]; then
echo "It's alive!"
fi

# Test if a symlink exists
if [ -L /path/to/symlink ]; then
echo "It's a link!"
fi

# Test if anything exists or a symlink is not broken
if [ -e /path/to/mountain ]; then
echo "Because it's there!"
fi

# Test if anything DOES NOT exist or a symlink IS broken
if [ ! -e /path/to/mountain ]; then
echo "Because it's there!"
fi

# Test if a file DOES NOT exist
if [ ! -f /path/to/file ]; then
echo "It's alive!"
fi

# Test if a variable is the same as something (quotes are optional, but safe)
if [ "$variable" = "I am blue" ]; then
echo "It's a blueberry!"
fi

# Test if a variable is NOT the same as something (quotes are optional, but safe)
if [ "$variable" != "I am blue" ]; then
echo "It's a blueberry!"
fi
