#!/bin/sh

# This file explains how variables and shell scripts work

# This is a comment

## We have "commented" the line below so it is here, but does nothing:
#sed -i "s/$FOO/$BAR/" $FILE

# For $10 and above, use: ${10}

echo "These are the variables:
\$0: $0
\$1: $1
\$2: $2
\$3: $3"
